cdklabs/cdklabs-projen-project-types

.projen/deps.json, .projen/tasks.json, .projenrc.ts, package.json, src/common-options.ts, src/safer-upgrades.ts, test/__snapshots__/cdk.test.ts.snap, test/__snapshots__/cdklabs.test.ts.snap, yarn.lock
Basically `npm-check-updates` is introducing a lot of packages to the dependency tree and the single `yarn upgrade npm-check-updates` command appears to be causing the incorrect lockfile.
This change removes `npm-check-updates` from the dependency tree, in favor of calling it via `npx`. Thus solving the above problem.
=> fix(upgrades): upgrades failing with wrap-ansi ESM cannot be loaded

.projenrc.ts
It already is floating in `package.json`.
=> chore: make `projen` dependency floating in projen

.projen/tasks.json, src/common-options.ts, test/__snapshots__/cdk.test.ts.snap, test/__snapshots__/cdklabs.test.ts.snap
This leads to upgrades that immediately fail because the peerDependencies are not satisfied.
=> fix: peerDependencies are upgraded without devDependencies

.projen/tasks.json, src/safer-upgrades.ts, src/yarn/monorepo.ts, src/yarn/typescript-workspace.ts, test/__snapshots__/cdk.test.ts.snap, test/__snapshots__/cdklabs-monorepo.test.ts.snap, test/__snapshots__/cdklabs.test.ts.snap
We are moving to running `npm-check-updates` via `npx`, but forgot a couple of places.
Fixes #
=> fix: upgrade workflow does not work in monorepos

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/upgrade-dev-deps-main.yml, .github/workflows/upgrade-main.yml, .projen/deps.json, .projen/tasks.json, .projenrc.ts, package.json, src/cdklabs.ts, src/common-options.ts, test/__snapshots__/cdklabs.test.ts.snap, test/cdklabs.test.ts, yarn.lock
The newest version of jsii (`5.3`) requires Node18, but all our repos are still running Node16. Bump it to 18.
The types that come with Node18 no longer compile on old TypeScript versions. All cdklabs libraries were still using jsii `1.x`. Move them all to jsii `5.2` (Why not `5.3`? Because who needs to chase modernity so badly?)
Remove `SaferUpgrades` from the prototype, because it was yelling at me while running the tests.
Fixes #
=> fix: bump Node version, TypeScript version, remove SaferUpgrades

.projen/deps.json, .projenrc.ts, package.json
https://github.com/cdklabs/cdklabs-projen-project-types/pull/326 stopped upgrading peer dependencies with the explicit goal to define the widest range of compatibility possible, but missed to actually change the peer dependency version constraint to be wide
Fixes failing build on upgrade PRs.
=> fix: package claims to be incompatible with current projen versions

.github/workflows/release.yml, src/avoid-release-attempts.ts, src/common-options.ts, test/__snapshots__/cdk.test.ts.snap, test/__snapshots__/cdklabs.test.ts.snap
This only works because registries don't allow publishing over an existing version and publib treats attempts to do so as soft fails.
Hackport from https://github.com/projen/projen/pull/3252 to test this out in a controlled environment.
=> fix: release to X jobs are running even when not required

.github/workflows/release.yml, src/avoid-release-attempts.ts, test/__snapshots__/cdk.test.ts.snap, test/__snapshots__/cdklabs.test.ts.snap
In the CI system, the `releasetag.txt` file ends up in `dist/dist/releasetag.txt` for reasons. 
Also cleans up the output setting to be more resilient and human parseable.
=> fix(release): avoid release attempts incorrectly block the release

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/upgrade-dev-deps-main.yml, .github/workflows/upgrade-main.yml, src/cdklabs.ts, test/__snapshots__/cdklabs.test.ts.snap
Instead of hardcoding a Node version, use a floating specifier (`lts/*`).
This makes sure that when our dependencies eventually start to require newer Node versions in their `"engines"` fields, our upgrade pipeline doesn't grind to a halt.
=> fix: use floating LTS Node version

src/yarn/nx.ts, test/cdklabs-monorepo.test.ts
Fixes `.nx` directory being committed by self-mutation.
=> fix(yarn-monorepo): gitignore .nx directory

src/yarn/monorepo-release.ts, test/__snapshots__/cdklabs-monorepo.test.ts.snap, test/cdklabs-monorepo.test.ts
A upstream fix in projen https://github.com/projen/projen/pull/3526 causes the YarnMonorepo release to fail.
This is because YarnMonorepo is doing some overly clever manipulation of the release workflow that probably should be pulled into projen core. This PR ports the upstream fix to YarnMonorepo.
=> fix(yarn): monorepo release publish jobs depend on jobs that do not exist

src/common-options.ts, test/__snapshots__/cdk.test.ts.snap, test/__snapshots__/cdklabs.test.ts.snap, test/cdk.test.ts, test/cdklabs.test.ts
When NPM release provenance is enabled, the package.json file must declare a repository url. By default this url isn't required except for JsiiProjects.
This PR adds a default repository url, computed from the org tenancy and package name.
It's a "best guess", but individual projects can still override the url if needed.
=> fix: Failed to validate repository information: package.json: "repository.url" is "", expected to match url from provenance

src/common-options.ts, test/cdk.test.ts
We are ignoring the user provided `npmAccess` configuration. This wasn't really a problem until https://github.com/cdklabs/cdklabs-projen-project-types/pull/614, which changed the default for private packages from `undefined` to `NpmAccess.RESTRICTED`. 
https://github.com/cdklabs/cdklabs-projen-project-types/blob/ca82d8eee4b8ac4d9fbe5ea04e9039238360ed71/src/common-options.ts#L34
While this change (arguably) makes sense, it causes problems with monorepos, where the root package must be private, resulting in the following [error](https://github.com/cdklabs/cdk-cloudformation/actions/runs/10967866796/job/30459544961):
```console
/home/runner/work/cdk-cloudformation/cdk-cloudformation/node_modules/projen/src/javascript/node-package.ts:961
throw new Error(
^
Error: "npmAccess" cannot be …
```
=> fix: `npmAccess` is ignored for `CdkTypeScriptProject`

src/yarn/typescript-workspace.ts, test/__snapshots__/cdklabs-monorepo.test.ts.snap
In the eslint VSCode plugin, the working directory in which `eslintrc.js` is loaded is not the project directory, and the JS file fails to load the `.json` file that's right next to it.
Include the directory of the file itself, which is guaranteed to be correct.
Fixes #
=> fix(eslint): update `eslintrc.js` to look in right directory

README.md
The new projen release adds features to control the version bump feature. These features are automatically published via `cdklabs-projen-project-types` as well.
Fixes #
=> feat: expose new projen features

API.md, src/yarn/typescript-workspace-release.ts
This value needed to be manually copied.
=> feat: monorepo support passing on `nextVersionCommand`

API.md, src/yarn/monorepo.ts, src/yarn/typescript-workspace.ts, test/cdklabs-monorepo.test.ts
Without this directive, the dependency will be hoisted to a top-level `node_modules` directory, but if it's there NPM will not bundle it when running `npm pack`.
=> fix: bundled dependencies should lead to a Yarn nohoist directive

src/cdk-cli-integ-tests.ts, test/__snapshots__/cdk-cli-integ-tests.test.ts.snap
- The way we configured the default registry (`npm config set registry`) doesn't work for some reason. Write directly to `~/.npmrc`, this method does work.
- The lib version can and must be different from the CLI version, so look it up and pass it to the integ test suite.
Fixes #
=> fix(cli-test-workflow): default registry doesn't work, and add lib version

src/cdk-cli-integ-tests.ts, test/__snapshots__/cdk-cli-integ-tests.test.ts.snap, test/cdk-cli-integ-tests.test.ts
We used to publish *all* `tgz` files, but only accepted select packages into the Verdaccio registry. That meant all non-accepted packages were proxied, and we would try to publish those to upstream npmjs.com which would fail.
In this change, publish exactly those tarballs that we accept into Verdaccio and no others.
=> fix(cdk-cli-integ): publish only specific packages

src/cdk-cli-integ-tests.ts, test/__snapshots__/cdk-cli-integ-tests.test.ts.snap
This flag is necessary to indicate the new versioning.
=> fix(cli-test-workflow): flip the flag indicating the version of cli-lib-alpha

API.md, src/cdk-cli-integ-tests.ts, test/__snapshots__/cdk-cli-integ-tests.test.ts.snap
In https://github.com/cdklabs/cdklabs-projen-project-types/pull/780 I was a bit too hasty; the environment variable needed to be on the `integ` job instead of the `build` job, and I forgot to add a `bump` step.
Also, we need to set `$RELEASE=true` on the build, otherwise projen synthesis will reset all version numbers.
We also need to make sure to fetch all tags on checkout, otherwise the version bumping will not work.
Fix those issues in this PR.
=> fix(cli-test-workflow): add bump command and set env vars

src/cdk-cli-integ-tests.ts, test/__snapshots__/cdk-cli-integ-tests.test.ts.snap
We use merge queues: if the tests are required they need to report success so they need to trigger. Don't actually do the tests again though, they take forever and we already ran them.
=> fix(cli-test-workflow): trigger on merge queues but don't do the run

src/cdk-cli-integ-tests.ts
The brace expansion in bash only works for 2+ packages, it does nothing for 1 package.
=> fix(cli-tests-workflow): workflow breaks for only 1 local package

src/yarn/monorepo-release.ts, src/yarn/monorepo.ts
This is necessary to enable jsii builds in a monorepo.
=> fix(monorepo): make release internal accessible

API.md, src/yarn/typescript-workspace-release.ts, src/yarn/typescript-workspace.ts, test/cdklabs-monorepo.test.ts
Fixes `npmDistTag` being ignored in a monorepo.
=> fix(monorepo): npmDistTag is not working

src/yarn/monorepo-release.ts, src/yarn/typescript-workspace-release.ts, test/cdklabs-monorepo.test.ts
After implementing #795 our monorepo project started to get the warning:
```
👾 The `distTag` option is deprecated. Use the npmDistTag option instead.
```
While implementing the fix I noticed that some other options that a workspace package should be able to set are currently ignored. When calling `_renderJobsForBranch` for a workspace package, the global monorepo values would be used instead of the local project configuration.
In practice this has little impact beyond `npmDistTag`, since most of these options aren't actually used in any of the publisher jobs. The only other use is the `prerelease` option, which tells the GitHub release job to mark a release as prerelease (or not). You could observe the wrong behavior on a current `cdk-assets` …
=> fix(monorepo): warning "The `distTag` option is deprecated. Use the npmDistTag option instead."

src/yarn/typescript-workspace-release.ts, test/__snapshots__/cdklabs-monorepo.test.ts.snap, test/cdklabs-monorepo.test.ts
Previously monorepo packages were released without provenance statements.
=> fix(monorepo): npm provenance is not respected

src/cdk-cli-integ-tests.ts, test/__snapshots__/cdk-cli-integ-tests.test.ts.snap
Allows skipping the integ workflow if the label `pr/exempt-integ-test` is added.
=> feat(cli-integ-tests): allow skipping integ tests with label

API.md, src/cdk-cli-integ-tests.ts, test/__snapshots__/cdk-cli-integ-tests.test.ts.snap, test/cdk-cli-integ-tests.test.ts
When the CLI integ tests run from a fork, the fork won't have the version tags and the candidate bumping fails (everything gets bumped to `0.0.0`, which causes tests to fail).
Instead, fetch tags from upstream.
I've opted to make the repo to fetch from an explicit parameter; I could have guessed that the repo would be `aws/<fork-name>`, but that just seemed like another avenue to get subtle bugs in the future.
Since this is now a newly required parameter which is breaking, I might as well remove the parameter that was only temporarily there for the duration of the migration.
=> fix(cli-integ-tests)!: fetch tags from upstream

src/cdk-cli-integ-tests.ts, test/__snapshots__/cdk-cli-integ-tests.test.ts.snap
We have to fetch over HTTPS because the workflow has no ssh auth set up.
Also reset fetch depth to only fetch 1 commit.
=> fix(cli-integ-tests): fetch tags from another URL

API.md, src/cdk-cli-integ-tests.ts, test/__snapshots__/cdk-cli-integ-tests.test.ts.snap, test/cdk-cli-integ-tests.test.ts
Allows configuring that upstream versions are visible for select packages.
This will be used for `@aws-cdk/cloud-assembly-schema`, which we will need available under the new version (for `cdk-assets`) as well as under an old version (for `aws-cdk-lib`).
=> feat(cli-integ-test): allow configuring upstream versions

.github/workflows/upgrade-dev-deps-main.yml, .github/workflows/upgrade-main.yml, API.md, projenrc/cdk-construct-library-options.ts, src/cdk-construct-library-options.ts, src/common-options.ts, test/__snapshots__/cdk.test.ts.snap, test/__snapshots__/cdklabs.test.ts.snap
This reduces the automatic dependency upgrade frequency of CDKLabs repos to once a week instead of daily.
Motivation:
Also remove the options that falsely give you an idea that this behavior can be configured on a per-repository basis. It cannot.
=> fix: reduce dependency upgrade frequency to once a week

src/yarn/gather-versions.exec.ts, src/yarn/gather-versions.task.ts, test/__snapshots__/cdklabs-monorepo.test.ts.snap, test/gather-versions.test.ts
When I simplified the command-line that `gather-versions` takes, I forgot to take out the condition that requires a minimum number of arguments.
The result is that `gather-versions` won't do anything thing for packages that have 0 or 1 workspace dependency; plus, the script didn't actually exit with an error code when that happened, so it was hard to detect.
Fix that in this PR, and also add a test that runs the `gather-versions` task properly from a projen monorepo config using `TaskRuntime`.
=> fix: gather-versions doesn't work for 0 or 1 dependencies

src/yarn/gather-versions.exec.ts, src/yarn/gather-versions.task.ts, test/gather-versions.test.ts
During refactoring I accidentally removed a `.join(' ')` so an
array stringifies fine but stringifies to the wrong string. Instead of:
```
a b c
```
it stringifies to
```
a,b,c
```
Which is not a command-line argument per package, but once command-line
argument with all packages in there.
=> fix: gather-versions doesn't work for >= 2 dependencies 

src/yarn/gather-versions.exec.ts, src/yarn/typescript-workspace-release.ts, test/__snapshots__/cdklabs-monorepo.test.ts.snap, test/gather-versions.test.ts
Releasing currently doesn't work since the monorepo release workflow changes `package.json` with exact references to monorepo packages like this:
```js
{ "monorepoDep": "^0.0.0"  }
// --> bump
{ "monorepoDep": "2.100.0"  }
// --> unbump
{ "monorepoDep": "0.0.0"  }
```
Which counts as a git diff and the `release` step fails.
=> fix(monorepo): gather-versions leaves repo in a state with diffs

src/cdk-cli-integ-tests.ts, test/__snapshots__/cdk-cli-integ-tests.test.ts.snap
The OIDC role created by atmosphere has a max duration of one hour, which is plenty.
=> fix: assume role session duration not compatible with atmosphere

API.md, src/cdk-cli-integ-tests.ts, test/cdk-cli-integ-tests.test.ts
This PR adds a new option to the CdkCliIntegTestsWorkflow component that allows specifying the maximum number of workers for running integration tests. 
The new  property is optional and when provided, it adds the `--maxWorkers` flag to the test command with the specified value.
This gives users more control over test parallelization in their CI workflows.
=> feat: add maxWorkers option to CdkCliIntegTestsWorkflow

API.md, src/yarn/gather-versions.exec.ts, src/yarn/typescript-workspace.ts, test/gather-versions.test.ts
Adds support for new and updated version types for workspace references, to allow for more flexible dependencies between packages in a monorepo:
- `any-minor` => `^1`
- `future-minor` => `^1.2.3`
- `any-patch` => `~1.2`
- `future-patch` => `~1.2.3`
- `exact` => `1.2.3`
- `any-future` => `>=1.2.3`
- `any` => `*`
The current types 'major' (=> `future-minor`), 'minor' (=> `future-patch`, 'minimal' (=> `any-future`) are renamed to more accurately reflect their effect.
=> feat(yarn)!: add extended version types for workspace references

README.md
In https://github.com/cdklabs/cdklabs-projen-project-types/pull/870, the package with updated with a new `npmTrustedPublishers` property [that was introduced to projen](https://github.com/projen/projen/pull/4321), we would like to start using this property in the CLI repository. 
Problem is, the PR didn't trigger a release because it was a `chore`. We should fix our releasable commits mechanism - but for now, i'd like to force a release.  
So this PR has no changes, expect it is marked with `feat`, so it will trigger a release.
=> feat: trusted publishers
